In [1]:
import numpy as np
matrix_a=np.array([[1,2,3,4],[5,6,7,8],[8,5,3,9]])
matrix_b=np.array([[5,9,4,0],[2,6,9,3],[8,0,2,1]])


In [2]:
matrix_a.ndim


2

In [3]:
matrix_b.ndim

2

In [4]:
matrix_a.shape



(3, 4)

In [5]:
matrix_b.shape

(3, 4)

In [6]:
np.add(matrix_a,matrix_b)


array([[ 6, 11,  7,  4],
       [ 7, 12, 16, 11],
       [16,  5,  5, 10]])

In [7]:
np.subtract(matrix_a,matrix_b)

array([[-4, -7, -1,  4],
       [ 3,  0, -2,  5],
       [ 0,  5,  1,  8]])

In [8]:
matrix_a*matrix_b


array([[ 5, 18, 12,  0],
       [10, 36, 63, 24],
       [64,  0,  6,  9]])

In [9]:
trans_a=matrix_a.T
trans_a

array([[1, 5, 8],
       [2, 6, 5],
       [3, 7, 3],
       [4, 8, 9]])

In [10]:
np.matmul(matrix_a,trans_a)

array([[ 30,  70,  63],
       [ 70, 174, 163],
       [ 63, 163, 179]])

In [11]:
np.average(matrix_b)
np.mean(matrix_b)
np.std(matrix_b)


3.1743328257901515

In [12]:
np.mean(matrix_b)

4.083333333333333

In [13]:
np.std(matrix_b)

3.1743328257901515

In [14]:
np.max(matrix_a,axis=0)

array([8, 6, 7, 9])

In [15]:
np.max(matrix_a,axis=1)

array([4, 8, 9])

In [16]:
np.min(matrix_b)

0

In [17]:
a=matrix_b.reshape(2,6)
a

array([[5, 9, 4, 0, 2, 6],
       [9, 3, 8, 0, 2, 1]])