In [2]:
import numpy as np
row_a=np.array([[1,2,3]])
row_a

array([[1, 2, 3]])

In [3]:
column_a=np.array([[1],[2],[3]])
column_a

array([[1],
       [2],
       [3]])

In [5]:
trans_column_a=column_a.T
trans_column_a

array([[1, 2, 3]])

In [6]:
np.dot(column_a,column_a)

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [7]:
np.dot(row_a,row_a)

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [8]:
np.add(column_a,row_a)

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])