In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
tr=pd.read_csv('data3.csv')
tr

D  X1  X2  X3  X4  X5  X6
0    0   3   3   3   4   2   4
1    0   3   2   3   5   4   3
2    1   5   3   3   3   3   5
3    0   5   4   3   3   3   5
4    0   5   4   3   3   3   5
..  ..  ..  ..  ..  ..  ..  ..
124  1   5   2   4   4   2   3
125  0   5   3   3   4   4   5
126  0   5   3   3   4   4   4
127  0   3   2   3   3   5   4
128  0   4   1   3   3   3   4

[129 rows x 7 columns]

In [3]:
total=tr.shape[0]
total

129

In [4]:
frqzero=tr['D'][tr['D']==0].count()
frqzero

59

In [5]:
frqone=tr['D'][tr['D']==1].count()
frqone

70

In [6]:
perzero=frqzero/total
perzero

0.4573643410852713

In [7]:
perone=frqone/total
perone

0.5426356589147286

In [8]:
czero=np.zeros((5,6))
czero

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
cone=np.zeros((5,6))
cone

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
tr['X1'][tr['D']==1][tr['X1']==3].count()

7

In [11]:
tr.X1.value_counts()

5    62
4    43
3    23
1     1
Name: X1, dtype: int64

In [12]:
tr.X2.value_counts()

3    40
2    37
1    28
4    18
5     6
Name: X2, dtype: int64

In [13]:
tr.X3.value_counts()

3    59
4    33
2    16
5    15
1     6
Name: X3, dtype: int64

In [14]:
tr.X4.value_counts()

4    51
3    48
5    23
2     6
1     1
Name: X4, dtype: int64

In [15]:
tr.X5.value_counts()

4    52
5    28
3    26
2    17
1     6
Name: X5, dtype: int64

In [16]:
tr.X6.value_counts()

5    54
4    52
3    21
2     1
1     1
Name: X6, dtype: int64

In [17]:
'X'+str(1)

'X1'

In [36]:
for i in range(0,6):
    for j in range(0,5):
        czero[j][i]=tr['X'+str(i+1)][tr['D']==0][tr['X'+str(i+1)]==j+1].count()

In [37]:
czero

array([[ 1., 15.,  4.,  0.,  5.,  1.],
       [ 0., 14.,  7.,  5.,  9.,  1.],
       [16., 18., 34., 24., 15., 16.],
       [25., 10.,  9., 21., 22., 24.],
       [17.,  2.,  5.,  9.,  8., 17.]])

In [31]:
for i in range(0,6):
    for j in range(0,5):
        cone[j][i]=tr['X'+str(i+1)][tr['D']==1][tr['X'+str(i+1)]==j+1].count()

In [32]:
cone

array([[ 0., 13.,  2.,  1.,  1.,  0.],
       [ 0., 23.,  9.,  1.,  8.,  0.],
       [ 7., 22., 25., 24., 11.,  5.],
       [18.,  8., 24., 30., 30., 28.],
       [45.,  4., 10., 14., 20., 37.]])

In [22]:
czero=czero/frqzero
czero

array([[0.01694915, 0.25423729, 0.06779661, 0.        , 0.08474576,
        0.01694915],
       [0.        , 0.23728814, 0.11864407, 0.08474576, 0.15254237,
        0.01694915],
       [0.27118644, 0.30508475, 0.57627119, 0.40677966, 0.25423729,
        0.27118644],
       [0.42372881, 0.16949153, 0.15254237, 0.3559322 , 0.37288136,
        0.40677966],
       [0.28813559, 0.03389831, 0.08474576, 0.15254237, 0.13559322,
        0.28813559]])

In [23]:
cone=cone/frqone
cone

array([[0.        , 0.18571429, 0.02857143, 0.01428571, 0.01428571,
        0.        ],
       [0.        , 0.32857143, 0.12857143, 0.01428571, 0.11428571,
        0.        ],
       [0.1       , 0.31428571, 0.35714286, 0.34285714, 0.15714286,
        0.07142857],
       [0.25714286, 0.11428571, 0.34285714, 0.42857143, 0.42857143,
        0.4       ],
       [0.64285714, 0.05714286, 0.14285714, 0.2       , 0.28571429,
        0.52857143]])

In [24]:
zeropro=np.zeros((6))
onepro=np.zeros((6))

In [25]:
for i in range(0,5):
    for j in range(0,6):
        if(czero[i][j] == 0):
            onepro[j] = onepro[j]+1
zeropro

array([1., 0., 0., 1., 0., 0.])

In [27]:
for i in range(0,5):
    for j in range(0,6):
        if(cone[i][j] == 0):
            onepro[j] = onepro[j]+1
onepro

array([2., 0., 0., 0., 0., 2.])

In [33]:
clzzeropro = np.zeros((5,6))
clzonepro = np.zeros((5,6))


In [35]:
for n in range(0,6):
    if(onepro[n]>0):
        for j in range(0,5):
            clzonepro[j][n] = (cone[j][n]+1)/(frqone+5)
    else:
        for j in range(0,5):
            clzonepro[j][n] = cone[j][n]/frqone
clzonepro

array([[0.01333333, 0.18571429, 0.02857143, 0.01428571, 0.01428571,
        0.01333333],
       [0.01333333, 0.32857143, 0.12857143, 0.01428571, 0.11428571,
        0.01333333],
       [0.10666667, 0.31428571, 0.35714286, 0.34285714, 0.15714286,
        0.08      ],
       [0.25333333, 0.11428571, 0.34285714, 0.42857143, 0.42857143,
        0.38666667],
       [0.61333333, 0.05714286, 0.14285714, 0.2       , 0.28571429,
        0.50666667]])

In [39]:
for n in range(0,6):
    if(zeropro[n]>0):
        for j in range(0,5):
            clzzeropro[j][n] = (czero[j][n]+1)/(frqzero+5)
    else:
        for j in range(0,5):
            clzzeropro[j][n] = czero[j][n]/frqzero
clzzeropro

array([[0.03125   , 0.25423729, 0.06779661, 0.015625  , 0.08474576,
        0.03125   ],
       [0.015625  , 0.23728814, 0.11864407, 0.09375   , 0.15254237,
        0.03125   ],
       [0.265625  , 0.30508475, 0.57627119, 0.390625  , 0.25423729,
        0.265625  ],
       [0.40625   , 0.16949153, 0.15254237, 0.34375   , 0.37288136,
        0.390625  ],
       [0.28125   , 0.03389831, 0.08474576, 0.15625   , 0.13559322,
        0.28125   ]])

In [40]:
ts=pd.read_csv('test3.csv')
ts

D  X1  X2  X3  X4  X5  X6
0   0   5   1   4   4   4   5
1   0   5   2   2   4   4   5
2   0   5   3   5   4   5   5
3   1   3   4   4   5   1   3
4   1   5   1   5   5   5   5
5   1   4   3   3   4   4   4
6   1   5   5   1   1   5   1
7   0   4   4   4   4   1   3
8   1   5   2   3   4   4   3
9   0   5   3   3   1   3   5
10  1   5   2   3   4   2   5
11  1   5   3   3   4   4   5
12  0   4   3   3   4   4   5
13  0   5   3   2   5   5   5

In [41]:
ts_total = ts.shape[0]
ts_total

14

In [42]:
#confusion matrix
true_pos = 0
true_neg = 0
false_pos = 0
false_neg = 0
for n in range(0,ts_total):
    a = 1
    b = 1
    for i in range(1,6):
        k = ts.at[n,'X'+str(i)]
        a = a*clzzeropro[k-1][i-1]
        b =b*clzonepro[k-1][i-1]
        if i == 5:
            break
    a = a*perzero
    b = b*perone
    if(a > b):
        predict = 0
    else:
        predict = 1
    result = ts.at[n,'D']
    if(result == 1 and predict == 1):
        true_pos = true_pos + 1
    elif(result == 1 and predict == 0):
        true_neg = true_neg + 1
    elif(result == 0 and predict == 1):
        false_pos = false_pos + 1
    else:
        false_neg = false_neg + 1

In [43]:
confusion = np.array([[true_pos,false_pos],[false_neg,true_neg]])
confusion

array([[5, 4],
       [3, 2]])

In [44]:
correctness=(true_pos+true_neg)/(true_pos+true_neg+false_pos+false_neg)
print("Correctness = ",correctness)

Correctness =  0.5


In [45]:
errorness=(false_pos+false_neg)/(true_pos+true_neg+false_pos+false_neg)
print("Errorness = ",errorness)

Errorness =  0.5


In [46]:
precision=true_pos/(true_pos+false_pos)
print("Precision = ",precision)

Precision =  0.5555555555555556


In [47]:
recall=true_pos/(true_pos+false_neg)
print("Recall = ",recall)

Recall =  0.625
